### ISSUE TITLE
Remove deprecated Python versions from the CI script

### ISSUE THREAD

**Issue by vsnever** [cherab/core#390]
Looks like `ubuntu-latest` switched to 22.04, and Python 3.6 is not available there. This results to `Error: Version 3.6 with arch x64 not found` when running the CI tests. Therefore, the list of Python versions must be updated in the CI script. Also, I suggest testing only with the oldest and the latest supported numpy versions for each Python version:
```
matrix:
  numpy: ["oldest-supported-numpy", "numpy"]
  python-version: ["3.7", "3.8", "3.9", "3.10"]

...
run: python -m pip install cython>=0.28 ${{ matrix.numpy }} scipy matplotlib pyopencl[pocl]==2022.1
```
@jacklovell, what do you think?
